language: node_js
node_js:
  - 0.10
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install aptitude
  - sudo -y aptitude install libgdal1-dev
  - sudo npm install -g tap
script:
  - npm test