environment:
  matrix:
    - nodejs_version: "0.8.26"
    - nodejs_version: "0.10.28"

platform:
  - x64
  - x86

install:
  - ps: Update-NodeJsInstallation $env:nodejs_version $env:Platform
  - node --version
  - npm --version
  - npm install --build-from-source
  - npm test

build: OFF
test: OFF
test_script: OFF
deploy: OFF