environment:
  matrix:
    - nodejs_version: "0.8.26"
    - nodejs_version: "0.10.28"

platform:
  - x86
  - x64

install:
  - SET PATH=C:\Program Files\7-Zip;%PATH%
  - SET PATH=C:\Python27;%PATH%
  - IF "%PLATFORM%"=="x86" CALL "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
  - IF "%PLATFORM%"=="x64" CALL "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64
  - ps: Start-FileDownload "https://mapnik.s3.amazonaws.com/dist/dev/libgdal_win_$env:PLATFORM.7z"
  - 7z x libgdal_win_%PLATFORM%.7z
  - ps: Update-NodeJsInstallation $env:nodejs_version $env:Platform
  - node --version
  - npm --version
  #because node-gyp bundled with node 0.8 doesn't know about --msvs_version=2013
  - npm install node-gyp
  - npm install --build-from-source --msvs_version=2013 --shared_gdal=c:/projects/node-gdal/deplibs/
  - npm test

build: OFF
test: OFF
test_script: OFF
deploy: OFF