environment:
  AWS_ACCESS_KEY_ID:
    secure: ihP9C8AMdicFGeffdKqgNG1O4n68jDHQPAZCB/IfuZg=
  AWS_SECRET_ACCESS_KEY:
    secure: G45Qz4paCV4VpsA939dz7i2PQiTdVOYwh1paZ3sGSdS9REKnLHB2cmToak8uAyHP
  matrix:
    - nodejs_version: "0.8.26"
    - nodejs_version: "0.10.29"
    # - nodejs_version: "0.11.13"

platform:
  - x86
  - x64

install:
  - SET PATH=C:\Program Files\7-Zip;%PATH%
  - SET PATH=C:\Python27;%PATH%
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - SET PATH=%APPDATA%\npm;%PATH%
  - SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
  - IF "%CM%" == "%CM:[publish binary]=%" (SET ENABLE_LOGGING=1)
  - ps: Write-Output '$env:Platform:' $env:Platform
  - ps: Write-Output '$env:nodejs_version' $env:nodejs_version
  - ps: Start-FileDownload "https://mapnik.s3.amazonaws.com/dist/dev/libgdal_win_$env:Platform.7z"
  - 7z x libgdal_win_%PLATFORM%.7z
  - ps: Update-NodeJsInstallation $env:nodejs_version $env:Platform
  - node --version
  - npm --version
  - npm install npm -g
  - npm --version
  # because node-gyp bundled with node 0.8 doesn't know about --msvs_version=2013
  - npm install node-gyp
  - npm install https://github.com/naturalatlas/mocha/archive/fix/333.tar.gz
  # build with/without logging depending on if we're pushing a binary
  - IF NOT "%ENABLE_LOGGING%" == "1" (npm install --build-from-source --msvs_version=2013 --shared_gdal=c:/projects/node-gdal/libs/)
  - IF "%ENABLE_LOGGING%" == "1" (npm install --build-from-source --msvs_version=2013 --shared_gdal=c:/projects/node-gdal/libs/ --enable-logging=true)
  - npm test
  - node_modules\.bin\node-pre-gyp package
  - ECHO commit message %CM%
  - ECHO pull request %APPVEYOR_PULL_REQUEST_NUMBER%
  - ECHO branch %APPVEYOR_REPO_BRANCH%
  - SET "IS_PR="&FOR /f "delims=0123456789" %%i IN ("%APPVEYOR_PULL_REQUEST_NUMBER%") DO SET IS_PR=%%i
  - IF NOT "%CM%" == "%CM:[publish binary]=%" (IF NOT DEFINED IS_PR (IF "%APPVEYOR_REPO_BRANCH%" == "master" node_modules\.bin\node-pre-gyp unpublish publish))
  - IF "%ENABLE_LOGGING%" == "1" (appveyor PushArtifact test/artifacts/log.txt)

build: OFF
test: OFF
test_script: OFF
deploy: OFF