environment:
  AWS_ACCESS_KEY_ID:
    secure: NQm//oI1+p9jLP5pkT7/FP4bmssn2/MwsiWlTscNEPc=
  AWS_SECRET_ACCESS_KEY:
    secure: DnAtyHwtPDeRgk28JdsGZALFhpYH3wmdJ5nQwrh1khRSK3KZLjkz8Qk9gGw+BuiV
  matrix:
    - nodejs_version: "0.8.26"
    - nodejs_version: "0.10.29"
    # - nodejs_version: "0.11.13"

platform:
  - x86
  - x64

install:
  - SET PATH=C:\Program Files\7-Zip;%PATH%
  - SET PATH=C:\Python27;%PATH%
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - ps: Write-Output $env:Platform
  - ps: Start-FileDownload "https://mapnik.s3.amazonaws.com/dist/dev/libgdal_win_$env:Platform.7z"
  - 7z x libgdal_win_%PLATFORM%.7z
  - ps: Update-NodeJsInstallation $env:nodejs_version $env:Platform
  - node --version
  - npm --version
  # because node-gyp bundled with node 0.8 doesn't know about --msvs_version=2013
  - npm install node-gyp
  - npm install --build-from-source --msvs_version=2013 --shared_gdal=c:/projects/node-gdal/libs/
  - npm test
  - node_modules\.bin\node-pre-gyp package
  - SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
  - ECHO commit message %CM%
  - if not "%CM%" == "%CM:[publish binary]=%" node_modules\.bin\node-pre-gyp publish

build: OFF
test: OFF
test_script: OFF
deploy: OFF