os: Visual Studio 2015

environment:
  AWS_ACCESS_KEY_ID:
    secure: ihP9C8AMdicFGeffdKqgNG1O4n68jDHQPAZCB/IfuZg=
  AWS_SECRET_ACCESS_KEY:
    secure: G45Qz4paCV4VpsA939dz7i2PQiTdVOYwh1paZ3sGSdS9REKnLHB2cmToak8uAyHP
  matrix:
    - nodejs_version: 0.10
      msvs_toolset: 14
      platform: x64
    - nodejs_version: 0.10
      msvs_toolset: 14
      platform: x86
    # Fixed at version until https://github.com/nodejs/node/issues/12244 is resolved by nodejs
    - nodejs_version: 4.8.1
      msvs_toolset: 14
      platform: x64
    - nodejs_version: 4.8.1
      msvs_toolset: 14
      platform: x86
    # Fixed at version until https://github.com/nodejs/node/issues/12244 is resolved by nodejs
    - nodejs_version: 6.10.1
      msvs_toolset: 14
      platform: x64
    - nodejs_version: 6.10.1
      msvs_toolset: 14
      platform: x86
    - nodejs_version: 8
      msvs_toolset: 14
      platform: x64
    - nodejs_version: 8
      msvs_toolset: 14
      platform: x86

artifacts:
  - path: test/artifacts/*.txt
    name: Test Logs

install:
  - ps: Start-FileDownload 'https://github.com/mapbox/ci-scripts/raw/master/node/ci-cpp.bat' -FileName ci.bat
  - CALL ci.bat

build: OFF
test: OFF
deploy: OFF
